name: Lint and Format Check

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Enable corepack and activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.17.1 --activate

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        id: eslint
        run: |
          echo "::notice::Running ESLint check..."
          if ! pnpm lint; then
            echo "::error::ESLint found issues in your code"
            echo "::notice::Run 'pnpm lint:fix' to automatically fix some issues"
            exit 1
          fi

      - name: Run Prettier check
        id: prettier
        run: |
          echo "::notice::Running Prettier format check..."
          if ! pnpm format:check; then
            echo "::error::Code formatting issues found"
            echo "::notice::Run 'pnpm format' to fix formatting issues"
            exit 1
          fi

      - name: Success notification
        if: success()
        run: |
          echo "::notice::All linting and formatting checks passed! ✅"
